language: java
jdk:
  - openjdk14

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients: antonpuckich@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="abbfe91d-fdb9-41f5-a1f3-13768fb0791b"
